apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%" 
      maxUnavailable: "25%" 
  replicas: 5
  selector:
    matchLabels:
      app: api
  template: 
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080" 
      labels:
        app: api            
    spec:
      containers:
      - name: api
        image: rof1966/api-produto:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: MONGODB_URI
            value: mongodb://mongodbuser:mongodbpwd@mongo-service:27017/admin
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
      

        
